version: "3.9"
services:
  app:
    build: .
    working_dir: /app
    command: ["npm", "run", "dev"]
    volumes:
      - ./:/app
    ports:
      - 127.0.0.1:3700:3000
      - 127.0.0.1:3701:24678

  web:
    image: caddy:2.6.2-alpine
    volumes:
      - ./public:/usr/share/caddy
    ports:
      - 127.0.0.1:8073:80
